{% set version = "0.8.0" %}

package:
  name: signac-flow
  version: {{ version }}

source:
  url: https://github.com/glotzerlab/signac-flow/archive/v{{ version }}.tar.gz
  sha256: 90be38b4ede668dcfd5eba7bb275df518b772dec9a57f92c9502d2a2e3344733

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - signac >=1.0.0
    - jinja2 >=2.8
    - cloudpickle
    - deprecation >=2

test:
  imports:
    - flow

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Project workflow management for signac projects.'
  description: |
    The signac-flow tool provides the basic components to setup simple to
    complex workflows for signac projects. That includes the definition of
    data pipelines, execution of data space operations and the submission
    of operations to high-performance super computers.
    The implementation is in pure Python, requires signac and is tested for
    Python versions 2.7 and 3.5+.
  doc_url: https://signac-flow.readthedocs.io
  dev_url: https://github.com/glotzerlab/signac-flow

extra:
  recipe-maintainers:
    - csadorf
    - vyasr
    - bdice
