{% set version = "0.10.0" %}

package:
  name: signac-flow
  version: {{ version }}

source:
  url: https://github.com/glotzerlab/signac-flow/archive/v{{ version }}.tar.gz
  sha256: 16a67d704daeb900cb7d06f5f84f59bf50ae36918b1a30757e0a52f79fb642fa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - flow = flow.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - cloudpickle
    - deprecation >=2
    - jinja2 >=2.8
    - python >=3.6
    - signac >=1.0.0
    - tqdm >=4.35.0

test:
  imports:
    - flow

about:
  home: https://signac.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Workflow management for signac projects.
  description: |
    The signac-flow tool provides the basic components to setup simple to
    complex workflows for signac projects. That includes the definition of
    data pipelines, execution of data space operations and the submission
    of operations to high-performance super computers.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-flow

extra:
  recipe-maintainers:
    - bdice
    - csadorf
    - mikemhenry
    - vyasr
