travis:
  secure:
    BINSTAR_TOKEN: lIvkAnq8bWtdxvCs9qhd+3KwSu6/lZsKQ9SPVWptVlPq0OEQD3KQf92mbx91KI4VHOuXVwuOL4vWIiBlIV/2u9FoF4bplCkxwyEJNQYtQNP1SgGqDON95gbKze0/dACTegHmQ6B1jp4+WQ3GBkVwgjF00X3RuGegVSe42ycbAT+WeY/L4arpLf8miYZqmj1YjqaZ7bR8yttYR/ELNYrgRonRM0qP+XaH5Xxl7xkR/MMBROSXZkEcBgbrRXRiqkSXESIZB+7VGLrPLcFRoPhuTjXkAify96mqWHZkGunDswNK7AHLkSdziXvADnH1IskvFenTFdphNfc5n9iEmzs++uPd/D6TjDjbwgkNdI2X2rIMudPj+x+IfYjrHYvVyeuVlGFZf+OTYYLE8JkDzoiz4xM2Xj8pOCzaRY9gLiXR92yjjc1PF+Hx8s3VqUbNuz7AHyEh2b/1LmbuRlikQYHTn4qKLT1C92lX9lHqJ22HPb9N6Ngi4i1BgN4aueSQ8hdGaLDuuCt9obrmx/BPNCOvSiUz0AM/K8iX9FY7WYMfW6tHve1emthi/qY2jBA39Qj7/XtceUSFtHAOtIn35aPy5wi5bOZAyCviEHpEXYzenNCV7PhY8F6m0v3cHQyiHiTQgCd0swStzCmxy5ILBu2T2hM32PvJUeKq64ku2tRwBHA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
