travis:
  secure:
    BINSTAR_TOKEN: N8sWpX7gT8UzdVIyF/ZJQaAMhmaHt+BnMP1xp87uKUFWZbi5yliXhvRNKfoCqrqurXFOltMLzSMH53B6Vf4kysURM1OjO4qItN7Ut8LvrcwATtuFgaBB56ODIUGvKv9EGmGxU/eia6AK36Hsd8TY4tsWeRHyebQveaVnhf5Awn6HBCbSQv5XLDOnF0D+NlhAwL3OjKG/F+twDtCSpuwz3eschHpOSQBUm94sL0Y3Vui/POeW0irzdKq7E8KN9zmNhOelwLhBZxOtq/kwoA4oeawd1CMpM7HA2Zmu8oY/42vmzkZzDryE0CKZLdLxlb4oVWlInLM2/uf5Qz7X//MyP/GG5vyuzBEAP1JN9d7lUA4P1h78GwDkewjHep1Mc5RYDbRGK1uRLpWdLDHUJmbhyMa06UJWhytL2D9grxSjFTWCyevr1dyCKquXfnCutYu2KB4YPl3SmiVJxHzR0zHrEPtrPxsAcbHgObLXX72udwgsXxiHvq6khrzJTlm3vvmvDVswtKmqXTGHGrBN5neBA2IDqvRp2tx4OGJ7rLld+FC0BZWddCz7lQl1GDu8gAoXuhuDk0OKVms63h7TgSxybU1e72gZJj6HdTdlr2S6yh8YOYrq8EvDpT/hlX8+mchU0OdP3IgzcjdGPhfwUrpwx81BWlQTISdBKJYcKcsrcPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
