travis:
  secure:
    BINSTAR_TOKEN: OJdhsKQQgUhNHkAxIfD3iOd0oUHd2N9G5Y8yNZzllE/WWuNDLi4lDG/ZbxlmIBAHS4RI1w2Cmx/d7ZK7uXgQYebC62b8kANQTMQFQLQhCm1fdWYZA1q0HiiO79zXrg95XyK0/UIJYdjGfsbI1XjIi4ubvNH5LlgIzGe8SxT3j78tAP9PGjf4+pkNQjwflS2+wOBnx0vQJdtqLnf6wZWoGWk0l9rcw3ovYIKtneWPVK+5wNvmTUMkpUG28omBeERmGqSt+I9htA81ENEKphw62sGICpYH79xS3RyELR/ttz6cCOdNcJ3dWJTgVkIKqCkX589QxEo66ha373eLb2zORDwVHqgvwU9AhTABIl5ez8hyHE760RTn7O5l26BdRbAKCv3QBBeKpcpAVV/AvEnLajIa9Dch1uxEvBQH5aHWpDnAVYDaXAmBvX5p/h+0GSQMHZoHfnWoEO1r14nCWjZFVO/yKQR2GgZzI38jDYUMI6Szv+8N4F6czyaVmxfRPkoel5RK4hYlH7B+OzyvSzul8WCSs0A1NqHZmGn6HlT9dmRxVuggGKeIcpikXPkMqEmIO5wtrx51UZe9YQEqBgjdWA9SG0Z7GioswF7vA4ExlXpBe6BnNZwGbaCsQr8bWhwZW39pocrf9FX3LA9uPVfAfbnyhGsifEqp+j8scuyx95Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
